# Generated by Django 2.2.5 on 2021-02-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20210228_0217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookedDay',
        ),
    ]
